services:
  - type: web
    name: riadscircle-static-site
    runtime: static
    buildCommand: ""
    staticPublishPath: "/"
    repo: https://github.com/YOUR_USERNAME/YOUR_REPOSITORY
    branch: main
    envVars: {}
